import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marqrue from "@/component/Marqrue";
import { Toaster } from "react-hot-toast";


const notoSerifbengali = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin","bengali"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifbengali.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
             {/* Marquee */}
      <Marqrue />
      <div className="container mx-auto">
      {children}
      </div>
      <Toaster></Toaster>
        </body>
    </html>
  );
}
